package com.a4tech.shipping.iservice;

import java.util.List;
import java.util.Map;

import com.a4tech.dao.entity.AxleWheelTypeEntity;
import com.a4tech.dao.entity.AxleWheelnfoEntity;
import com.a4tech.dao.entity.DistrictWiseNormalLoadCapacity;
import com.a4tech.dao.entity.LangitudeAndLatitudeMap;
import com.a4tech.dao.entity.TruckHistoryDetailsEntity;
import com.a4tech.dao.entity.UsedTrucksEntity;
import com.a4tech.map.model.Address;
import com.a4tech.shipping.model.AvailableTrucks;
import com.a4tech.shipping.model.AxleWheelConfiguration;
import com.a4tech.shipping.model.ChannelConfiguration;
import com.a4tech.shipping.model.DistrictClubOrdByPass;
import com.a4tech.shipping.model.IntellishipModelByMaterial;
import com.a4tech.shipping.model.NormalLoadConfiguration;
import com.a4tech.shipping.model.OrderGroup;
import com.a4tech.shipping.model.ShippingDeliveryOrder;
import com.a4tech.shipping.model.ShippingDetails1;
import com.a4tech.shipping.model.ShippingOrdersReAssignModel;
import com.a4tech.shipping.model.TruckHistoryDetail;
import com.a4tech.shipping.model.UsedTrucksModel;
import com.a4tech.shipping.model.User;

public interface IShippingOrder {
  public List<ShippingDetails1> getAllShippingOrders();
  public List<ShippingDetails1> getShippingDetailsByDate(String date);
  public List<AvailableTrucks> getAllAvilableTrucks();
  public void saveOrderGroup(OrderGroup orderGroup);
  public List<OrderGroup> getAllGroupOrderList();
  public List<OrderGroup> getOrderGroupByDate(String date);
  public ShippingDetails1 getShippingDetails(String orderNo);
  public List<String> getOrderNoByTruck(String truckNo);
  public void updateOrderGroupFlag(String delivaryNo);
  public List<Address> getLatitudeAndLongitude(String truckNo);
  public void deleteAllGroupOrders(String tableName);
  public int generateShippingOrderId(ShippingDeliveryOrder shippingDelivary);
  public void saveDistrictWiseNormalLoad(NormalLoadConfiguration normal);
  public List<DistrictWiseNormalLoadCapacity> getAllDistrictWiseLoads();
  public DistrictWiseNormalLoadCapacity getDistrictTruckLoad(String districtName);
  public void updateDistrictWiseNormalLoad(NormalLoadConfiguration normal);
  public List<TruckHistoryDetailsEntity> getAllTrucksHistoryDetails();
  public List<TruckHistoryDetailsEntity> getSearchTrucksHistoryDetails(String value,String type);
  public void saveAxleWheelConfiguration(AxleWheelConfiguration axleWheelConfig);
  public void saveOrUpdateDistrictClubOrdByPass(DistrictClubOrdByPass districtByPass);
  public List<DistrictClubOrdByPass> getAllDistrictClubOrdByPass();
  public AxleWheelTypeEntity getAxlewheel(String wheelType);
  public List<AxleWheelTypeEntity> getAllAxleWheelTypeEntity();
  public List<AxleWheelnfoEntity> getWheelTypeInfo(String name);
  public List<TruckHistoryDetail> getAllPreviousTrucksByDistName(String distName);
  public void saveShippingOrderReAssign(ShippingOrdersReAssignModel shippingEntity); 
  public List<ShippingDetails1> getAllReAssignOrdersBasedOnTruckNo(String truck);
  public TruckHistoryDetailsEntity getDistrictDetails(String distName,String truckNo);
  public List<AvailableTrucks> getAllAvailableTrucksByAxleType(String axleType);
  public void deleteOrderByPassDistrict(Integer id);
 // public void updateDistrictClubOrdByPass(DistrictClubOrdByPass districtByPass);
  public void saveLatitudeAndLongitudeVals(LangitudeAndLatitudeMap longi);
  public Map<String, String> getAllLatitudeAndLongitudeVals();
  
  public User getUserDetails(String name);
  public void saveShippingFinalOrders(IntellishipModelByMaterial shippingFinalOrders);
  public List<IntellishipModelByMaterial> getAllShippingFinalOrders();
  public List<ChannelConfiguration> getAllChannelConfigurations();
  public void saveOrUpdatechannelConfiguration(ChannelConfiguration channelConfig);
  public void deleteChannelConfiguration(Integer id);
  public void saveChannelSequence(String sequence);
  public String getChannelSequence();
  public List<UsedTrucksModel> getAllUsedTrucks();
  public void saveUsedTruck(UsedTrucksModel usedTruck);
  public void deleteTruckFromTruckPool(AvailableTrucks availableTruck);
  public void deleteOrderFromPendingList(ShippingDetails1 shipping);
  public void saveShippingOrderReAssign(List<ShippingOrdersReAssignModel> shippingReOrder);
  public UsedTrucksEntity getUsedTruckByTruckNo(String truckNo);
  public void saveTruckhistory(TruckHistoryDetailsEntity truckHistory,String districtName,String truckNo);
  public void updateAxleWheelerInfo(AxleWheelnfoEntity axleWheelerType);
  public void addAxleWheelerInfo(AxleWheelnfoEntity axleWheelerType);
  public void deleteAxleWheelerInfo(Integer wheelerId);
  public List<AxleWheelnfoEntity> getWheelTypeInfo();
}
